 ## Default Kibana configuration from kibana-docker.
 #from https://github.com/elastic/kibana-
 #docker/blob/master/build/kibana/config/kibana.yml
 #
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.security.enabled: true