filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              container.labels.collect_logs_with_filebeat: "true"
          config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              processors:
                - decode_json_fields:
                    when.equals:
                      docker.container.labels.decode_log_event_to_json_object: "true"
                    fields: ["message"]
                    target: ""
                    overwrite_keys: true

#filebeat.inputs:
#  - type: log
#    enabled: true
#    paths:
#    - /Users/julienfumanti/Documents/bitbucket/open-drive/*.log
#    json.keys_under_root: true
#    json.overwrite_keys: true
#    json.add_error_key: true
#    json.expand_keys: true

output.logstash:
  hosts: "logstash:5044"

logging.metrics.enabled: false

